const { GANReviewHTMLGenerator } = require("../modules/GANReviewHTMLGenerator");

// Babel is required to use ES6 module syntax
// Copy package.json and .babelrc from a project that already has this working
// Babel tutorial: https://www.sitepoint.com/babel-beginners-guide/

let hg = new GANReviewHTMLGenerator();

describe('getHTML(gaTitle)', () => {
	it(`Should inject $gaTitle into the form's HTML`, () => {
		let gaTitle = `UnqiueString~~~Test`;
		let output = 'UnqiueString~~~Test';
		expect(hg.getHTML(gaTitle)).toMatch(output); // don't forget, toMatch() checks using regex. it is not the same as toEqual()
	});

	it(`Should html escape $gaTitle before injecting it`, () => {
		let gaTitle = `UnqiueString~~~"&<>`;
		let output = 'UnqiueString~~~&quot;&amp;&lt;&gt;';
		expect(hg.getHTML(gaTitle)).toMatch(output); // don't forget, toMatch() checks using regex. it is not the same as toEqual()
	});
});

describe('getDefaultDisplayText(gaTitle)', () => {
	it(`Should handle no parentheses`, () => {
		let gaTitle = `Test`;
		let output = 'Test';
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle parentheses not in dictionary`, () => {
		let gaTitle = `Test (123)`;
		let output = 'Test (123)';
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle parentheses in dictionary suffixesThatTriggerItalics`, () => {
		let gaTitle = `Test (album)`;
		let output = `''Test'' (album)`;
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle parentheses in dictionary suffixesThatTriggerDoubleQuotes`, () => {
		let gaTitle = `Test (song)`;
		let output = '"Test" (song)';
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle parentheses in dictionary suffixesThatTriggerDoubleQuotesAndItalics`, () => {
		let gaTitle = `Test (30 Rock)`;
		let output = `"Test" (''30 Rock'')`;
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle long parentheses in dictionary suffixesThatTriggerDoubleQuotesAndItalics`, () => {
		let gaTitle = `Test (Test2 30 Rock)`;
		let output = `"Test" (''Test2 30 Rock'')`;
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});

	it(`Should handle Llegar a Ti (song)`, () => {
		let gaTitle = `Llegar a Ti (song)`;
		let output = `"Llegar a Ti" (song)`;
		expect(hg.getDefaultDisplayText(gaTitle)).toEqual(output);
	});
});

describe('makeTopicComboBoxOptionGroup(wikicode, category)', () => {
	it(`Normal`, () => {
		let topic = 'Art and architecture';
		let wikicode =
`<noinclude>
{{hatnote|[[#Art and architecture|'''↓  Skip to lists  ↓''']]}}
{{Wikipedia:Good article nominations/Tab header}}
{{Wikipedia:Good articles/Summary|shortcuts={{shortcut|WP:GA/AA}}}}
</noinclude><templatestyles src="Wikipedia:Good articles/styles.css"/>
__NOTOC__
<div class="wp-ga-topic">
==Art and architecture==
<includeonly><div class="wp-ga-topic-back">[[#Contents|back]]</div></includeonly>
<div class="wp-ga-topic-contents">
===Contents===
{{plainlist}}
* [[#Art|Art]]
* [[#Architecture|Architecture]]
{{endplainlist}}
</div>
<!--Start Art level 3 GA subtopic-->
<div class="mw-collapsible">
===[[File:Nuvola apps package graphics.svg|22px|left|alt=|link=]] Art===
<div class="wp-ga-topic-back">[[#Art and architecture|back]]</div>
<div class="mw-collapsible-content">
<!--The level 5 GA subtopics on this page may be first subdivided into new level 4 GA subtopics; see other GA topic pages-->
<!--The level 5 GA subtopics on this page may be subdivided into new level 5 GA subtopics and other level 5 GA subtopics may be added; see other GA topic pages-->

====Art====
{{#invoke:Good Articles|subsection|
[[Abel Tasman Monument]]
[[Akzidenz-Grotesk]]
[[Albert Pike Memorial]]
[[Allow Me (Portland, Oregon)|''Allow Me'' (Portland, Oregon)]]
[[Alma Mater (New York sculpture)|''Alma Mater'' (New York sculpture)]]
''[[Angel of the North]]''
''[[Angkor I]]''
[[Angolan pavilion]]
[[Antarctic Treaty issue]]
[[Art in early modern Scotland]]
[[Art in Medieval Scotland]]
[[Art in modern Scotland]]
''[[B of the Bang]]''
[[Art of Francisco Narváez in the University City of Caracas]]
[[Bara (genre)|''Bara'' (genre)]]
[[Barack Obama "Hope" poster]]
[[Batik]]
[[Bed hangings]]
[[Bembo]]
''[[Better Out Than In]]''
[[Benty Grange hanging bowl]]
[[Birds' Head Haggadah]]
[[Bois Protat]]
[[Bookwheel]]
[[Brushstrokes series]]
[[Burnside Fountain]]
[[Canons of page construction]]
[[Chain Reaction (sculpture)|''Chain Reaction'' (sculpture)]]
[[Changi Murals]]
[[Comedian (artwork)|''Comedian'' (artwork)]]
''[[Conductores de Venezuela]]''
''[[Confederate Defenders of Charleston]]''
''[[Cottontail on the Trail]]''
[[Crosby Garrett Helmet]]
[[Cueva de las Manos]]
[[Cup of the Ptolemies]]
''[[Demi's Birthday Suit]]''
[[The Dream (sculpture)|''The Dream'' (sculpture)]]
[[Droeshout portrait]]
[[Droste effect]]
[[Duncan & Miller Glass Company]]
[[Dupont Circle Fountain]]
[[English embroidery]]
[[Enlighten Canberra]]
[[Ehrhardt (typeface)]]
[[Equestrian statue of Charles Devens]]
[[Equestrian statue of George B. McClellan]]
[[Equestrian statue of George Henry Thomas]]
[[Equestrian statue of John A. Logan]]
[[Equestrian statue of John Brown Gordon]]
[[Equestrian statue of Philip Sheridan]]
[[Equestrian statue of Winfield Scott]]
''[[The Exaltation of the Flower]]''
[[Fostoria Glass Company]]
''[[Fountain for Company H]]''
''[[Fountain of the Great Lakes]]''
''[[Freydal]]''
[[Gallos (sculpture)|''Gallos'' (sculpture)]]
[[Garamond]]
''[[Gate to the Northwest Passage]]''
''[[Ghana Freedom]]''
[[Gill Sans]]
''[[Goshin]]''
''[[The Great Wave off Kanagawa]]''
''[[Guns into Plowshares]]''
''[[Güzel İstanbul]]''
[[Hallaton Helmet]]
[[Henry W. Maxwell Memorial]]
[[History of cardistry]]
[[Hoosier cabinet]]
[[The Irascibles]]
''[[Isambard Kingdom Brunel Standing Before the Launching Chains of the Great Eastern]]''
[[Islamic geometric patterns]]
''[[Jet Kiss]]''
[[Khalili Collection of Aramaic Documents]]
[[Khalili Collection of Enamels of the World]]
[[Khalili Collection of Hajj and the Arts of Pilgrimage]]
[[Khalili Collection of Japanese Art]]
[[Khalili Imperial Garniture]]
[[Kilim motifs]]
''[[Knife Edge Two Piece 1962–65]]''
''[[Kvinneakt]]''
[[Kwakiutl (statue)|''Kwakiutl'' (statue)]]
''[[Liberty Arming the Patriot]]''
''[[Liberty Bell (Portland, Oregon)]]''
[[Liminal space (aesthetic)]]
''[[Lion Attacking a Dromedary]]''
[[Liudhard medalet]]
''[[Lolicon]]''
[[Lovejoy Columns]]
[[Low-key photography]]
''[[Lunch atop a Skyscraper]]''
''[[Man at the Crossroads]]''
''[[Man Enters the Cosmos]]''
[[María Lionza (statue)|''María Lionza'' (statue)]]
[[Mathematics and art]]
[[Minnesota State Capitol artwork]]
''[[More Demi Moore]]''
[[Muisca raft]]
[[Murasaki Shikibu Nikki Emaki]]
[[National Treasure (Japan)]]
[[Natural dye]]
[[Navajo weaving]]
[[Nefertiti Bust]]
[[Paper clothing]]
''[[People's Bike Library of Portland]]''
[[Photography in Denmark]]
[[Photography in Sudan]]
[[Pioneer Square totem pole]]
[[Pod (sculpture)|''Pod'' (sculpture)]]
[[Prehistoric art in Scotland]]
[[The Quest (Portland, Oregon)|''The Quest'' (Portland, Oregon)]]
[[Rällinge statuette]]
[[Rebirth (sculpture)|''Rebirth'' (sculpture)]]
[[Report on the restitution of African cultural heritage]]
[[Richard Coeur de Lion (statue)|''Richard Coeur de Lion'' (statue)]]
''[[Robert E. Lee on Traveller]]''
''[[Sacred Cod]]''
[[Scottish art]]
[[Scottish art in the eighteenth century]]
[[Scottish art in the nineteenth century]]
''[[Shemanski Fountain]]''
[[Sleight of hand]]
''[[Soaring Stones]]''
[[Solovetsky Stone (Saint Petersburg)]]
[[Sprang]]
[[Star on the Mountain]]
[[Stars (M. C. Escher)|''Stars'' (M. C. Escher)]]
[[Statue of A'a from Rurutu]]
[[Statue of Abraham Lincoln (District of Columbia City Hall)]]
[[Statue of Alexander Wood]]
[[Statue of Ashurbanipal (San Francisco)]]
[[Statue of Christopher Columbus (Providence, Rhode Island)]]
[[Statue of David Farragut (Washington, D.C.)]]
[[Statue of Edward Colston]]
[[Statue of Elizabeth II, Lagos]]
[[Statue of George H. Perkins]]
[[Statue of Harvey W. Scott]]
[[Statue of Heydar Aliyev, Mexico City]]
[[Statue of James II, Trafalgar Square]]
[[Statue of James S. T. Stranahan]]
[[Statue of John Aaron Rawlins]]
[[Statue of Lenin (Seattle)]]
[[Statue of Michael Jordan]]
[[Statue of Vera Katz]]
[[Statue of William Francis Bartlett]]
[[Statue of William the Silent]]
''[[Stuckism]]''
[[Medieval stained glass in Sweden|Sweden, Medieval stained glass in]]
[[Sydney punchbowls]]
[[Ten Dollar Bill (Lichtenstein)|''Ten Dollar Bill'' (Lichtenstein)]]
[[Three Brothers (jewel)]]
[[Tipu's Tiger]]
[[Tolkien's artwork]]
[[Transformation playing card]]
[[Untitled (Richard Fleischner artwork at Alewife station)|''Untitled'' (Richard Fleischner artwork at Alewife station)]]
''[[Vanitas: Flesh Dress for an Albino Anorectic]]''
[[Venetian glass]]
[[Vénus de Quinipily]]
''[[View of the World from 9th Avenue]]''
[[Willie Gillis]]
[[Zodiac settle]]
}}

=====Painting=====
{{#invoke:Good Articles|subsection|
''[[A Boy with a Flying Squirrel]]''
''[[Arnold Comes of Age]]''
''[[Artist's Studio—Look Mickey]]''
[[Battle of Grunwald (Matejko)|''Battle of Grunwald'' (Matejko)]]
''[[Beauty Revealed]]''
''[[Big Painting No. 6]]''
''[[Bonaparte Crossing the Alps]]''
''[[Cleopatra and Caesar (painting)|Cleopatra and Caesar]]''
[[Constitution of 3 May 1791 (painting)|''Constitution of 3 May 1791'' (painting)]]
''[[The Conquest of Belgrade]]''
''[[The Cornfield]]''
''[[Decorating of the Bride]]''
''[[The Distrest Poet]]''
''[[Doni Tondo]]''
''[[The Dream of Ossian]]''
''[[Dynamism of a Dog on a Leash]]''
[[Evening Bells (painting)|''Evening Bells'' (painting)]]
[[The Fourth Estate (painting)|''The Fourth Estate'' (painting)]]
[[Freedom from Fear (painting)|''Freedom from Fear'' (painting)]]
[[Freedom of Speech (painting)|''Freedom of Speech'' (painting)]]
''[[Fresh Wind. Volga]]''
''[[The Funeral of the Anarchist Galli]]''
[[Gettysburg Cyclorama]]
''[[Girl in Mirror]]''
''[[Girl with Ball]]''
''[[Golf Ball]]''
''[[Grrrrrrrrrrr!!]]''
''[[Happy Brothers]]''
[[Haystacks (Monet series)|''Haystacks'' (Monet)]]
''[[Her Majesty Queen Elizabeth II – An 80th Birthday Portrait]]''
''[[I Can See the Whole Room...and There's Nobody in It!]]''
''[[The Icebergs]]''
[[Ink wash painting]]
''[[In the Ploughed Field: Spring]]''
''[[Ivan the Terrible and His Son Ivan]]''
''[[Kent vs Lancashire at Canterbury]]''
[[The Kiss (Munch)|''The Kiss'' (Munch)]]
[[Landscape painting in Scotland]]
''[[Langlois Bridge at Arles]]''
''[[La Scapigliata]]''
[[The Magpie (Monet)|''The Magpie'' (Monet)]]
''[[Marie Antoinette and Her Children]]''
''[[Midvinterblot]]''
''[[Mirth & Girth]]''
[[Naewat-dang shamanic paintings]]
''[[The Nightmare]]''
''[[Okay Hot-Shot, Okay!]]''
[[Olive Trees (Van Gogh series)]]
[[Packy mural]]
[[Paleoart]]
[[Pietro Annigoni's portraits of Elizabeth II]]
''[[A Polish Nobleman]]''
''[[Portrait of Adele Bloch-Bauer I]]''
[[Portrait of Madame Cézanne (Lichtenstein)|''Portrait of Madame Cézanne'']]
[[Portrait painting in Scotland]]
''[[The Proclamation of Dušan's Law Codex]]''
[[Prussian Homage (painting)|''Prussian Homage'' (painting)]]
[[P. S. Krøyer's paintings of Marie]]
[[Rejtan (painting)|''Rejtan'' (painting)]]
''[[The Rocky Mountains, Lander's Peak]]''
''[[Self-Portrait with Halo and Snake]]''
''[[Sigismunda mourning over the Heart of Guiscardo]]''
''[[Skaters in the Bois de Boulogne]]''
[[Stańczyk (painting)|''Stańczyk'' (painting)]]
''[[Still Life with Books]]''
[[Church murals in Sweden|Sweden, Church murals in]]
''[[Symphony in White, No. 1: The White Girl]]''
''[[Symphony in White, No. 2: The Little White Girl]]''
''[[Symphony in White, No. 3]]''
''[[The Takovo Uprising]]''
''[[There Comes Papa]]''
''[[Torpedo...Los!]]''
[[The Tribute Money (Masaccio)|''The Tribute Money'' (Masaccio)]]
''[[Tristan and Isolde (Egusquiza)]]''
''[[Vädersolstavlan]]''
''[[Virgin of Vladimir]]''
''[[A Vision of the Last Judgement]]''
[[Vladimirka (painting)|''Vladimirka'' (painting)]]
''[[Vršac triptych]]''
''[[The Wedding Dance]]''
[[White Mountain art]]
[[William Blake's illustrations of On the Morning of Christ's Nativity|William Blake's illustrations of ''On the Morning of Christ's Nativity'']]
[[Woodstock Mural]]
''[[The Wounded Montenegrin]]''
''[[Zawieszenie dzwonu Zygmunta]]''
}}

====Artists and art organizations====
{{#invoke:Good Articles|subsection|
[[1-54]]
[[Alexander Buchan (artist)|Alexander Buchan]]
[[Astri Aasen|Aasen, Astri]]
[[Ansel Adams|Adams, Ansel]]
[[Ivan Aivazovsky|Aivazovsky, Ivan]]
[[Lola Álvarez Bravo|Álvarez Bravo, Lola]]
[[Gene Amondson|Amondson, Gene]]
[[Ryan Ashley|Ashley, Ryan]]
[[Abel Azcona|Azcona, Abel]]
[[William Bliss Baker|Baker, William Bliss]]
[[Franzisca Baruch|Baruch, Franzisca]]
[[Jean-Michel Basquiat|Basquiat, Jean-Michel]]
[[John Bauer (illustrator)|Bauer, John]]
[[Antonio Berni|Berni, Antonio]]
[[Lorenza Böttner|Böttner, Lorenza]]
[[John Boydell|Boydell, John]]
[[Ernest Brooks (photographer)|Brooks, Ernest]]
[[Romaine Brooks|Brooks, Romaine]]
[[Edward Burne-Jones|Burne-Jones, Edward]]
[[Gasparo Cairano|Cairano, Gasparo]]
[[Edson Chagas|Chagas, Edson]]
[[Alonzo Clemons|Clemons, Alonzo]]
[[Joseph Clover (artist)|Clover, Joseph]]
[[Jack Coggins|Coggins, Jack]]
[[Cyril Colnik|Colnik, Cyril]]
[[Dar al-Kiswa]]
[[Giles Deacon|Deacon, Giles]]
[[Gürdal Duyar|Duyar, Gürdal]]
[[Mary Beth Edelson|Edelson, Mary Beth]]
[[M. C. Escher|Escher, M. C.]]
[[Timothy Everest|Everest, Timothy]]
[[Carl Eytel|Eytel, Carl]]
[[Vincent Figgins|Figgins, Vincent]]
[[Joanne Gair|Gair, Joanne]]
[[Aubrey Gibson|Gibson, Aubrey]]
[[Alfred Gilbert|Gilbert, Alfred]]
[[Luigi Domenico Gismondi|Gismondi, Luigi Domenico]]
[[Grandma Moses]]
[[Grey Gowrie]]
[[William Griswold (museum director)|Griswold, William (museum director)]]
[[Karoly Grosz (illustrator)|Grosz, Karoly (illustrator)]]
[[Han Sai Por]]
[[Mary Brewster Hazelton|Hazelton, Mary Brewster]]
[[Alberto Henschel|Henschel, Alberto]]
[[Barbara Howard (artist)|Howard, Barbara]]
[[Leslie Hunter|Hunter, Leslie]]
[[Invader (artist)]]
[[Maija Isola|Isola, Maija]]
[[Wadsworth Jarrell|Jarrell, Wadsworth]]
[[Rashid Johnson|Johnson, Rashid]]
[[William Johnson (artist)|Johnson, William]]
[[Thomas Johnston (engraver)|Johnston, Thomas]]
[[Einar Jolin|Jolin, Einar]]
[[William B. Jordan|Jordan, William B.]]
[[John Cantiloe Joy and William Joy|Joy, John Cantiloe and Joy, William]]
[[K Foundation]]
[[K Foundation art award]]
[[Kabukidō Enkyō]]
[[Nadia Kaabi-Linke|Kaabi-Linke, Nadia]]
[[Josepha Petrick Kemarre|Kemarre, Josie Petrick]]
[[Brian Kershisnik|Kershisnik, Brian]]
[[Hiroh Kikai|Kikai Hiroh]]
[[Isidore van Kinsbergen|Kinsbergen, Isidore van]]
[[Jack Kirby|Kirby, Jack]]
[[Astrid Kirchherr|Kirchherr, Astrid]]
[[Laura Knight|Knight, Laura]]
[[Knitta Please]]
[[Chaim Koppelman|Koppelman, Chaim]]
[[Maggie Laubser|Laubser, Maggie]]
[[Blanche Lazzell|Lazzell, Blanche]]
[[Leonardo da Vinci]]
[[Harvey Littleton|Littleton, Harvey]]
[[Thomas Lound|Lound, Thomas]]
[[Hamidou Maiga|Maiga, Hamidou]]
[[Jan Matejko|Matejko, Jan]]
[[Peter Matthews (artist)|Matthews, Peter]]
[[Han van Meegeren|Meegeren, Han van]]
[[Jean-Claude Mézières|Mézières, Jean-Claude]]
[[John Middleton (Norfolk artist)|Middleton, John]]
[[Kate Millett|Millett, Kate]]
[[Joan Mitchell|Mitchell, Joan]]
[[Alan Moore (war artist)|Moore, Alan]]
[[William Morris|Morris, William]]
[[Will Munro|Munro, Will]]
[[Hans Namuth|Namuth, Hans]]
[[Peggy Rockman Napaljarri|Napaljarri, Peggy Rockman]]
[[Linda Syddick Napaltjarri|Napaltjarri, Linda Syddick]]
[[Ngoia Pollard Napaltjarri|Napaltjarri, Ngoia Pollard]]
[[Susie Bootja Bootja Napaltjarri|Napaltjarri, Susie Bootja Bootja]]
[[Tjunkiya Napaltjarri|Napaltjarri, Tjunkiya]]
[[Louise Nevelson|Nevelson, Louise]]
[[Christopher R. W. Nevinson|Nevinson, Christopher R. W.]]
[[Audley Dean Nicols|Nicols, Audley Dean]]
[[Henry Ninham|Ninham, Henry]]
[[Billie Nipper|Nipper, Billie]]
[[Eleanor Norcross|Norcross, Eleanor]]
[[Ugochukwu-Smooth Nzewi|Nzewi, Ugochukwu-Smooth]]
[[Emeka Ogboh|Ogboh, Emeka]]
[[Olek (artist)]]
[[Rose O'Neill|O'Neill, Rose]]
[[Neri Oxman|Oxman, Neri]]
[[Susanna Paine|Paine, Susanna]]
[[Clara Elsene Peck|Peck, Clara Elsene]]
[[Harold H. Piffard|Piffard, Harold H.]]
[[Iso Rae|Rae, Iso]]
[[Alex Raymond|Raymond, Alex]]
[[Rembrandt]]
[[Auguste Rodin|Rodin, Auguste]]
[[William Rose (illustrator)|Rose, William]]
[[Dolly Rudeman|Rudeman, Dolly]]
[[Isaac Sailmaker|Sailmaker, Isaac]]
[[Ethel Sands|Sands, Ethel]]
[[Emily Sartain|Sartain, Emily]]
[[Charles Roscoe Savage|Savage, Charles Roscoe]]
[[Marjorie Schick|Schick, Marjorie]]
[[Obadiah Short|Short, Obadiah]]
[[James Sillett|Sillett, James]]
[[Skagen Painters]]
[[Ralph Stackpole|Stackpole, Ralph]]
[[Emily Stannard|Sannard, Emily]]
[[Joseph Stannard|Stannard, Joseph]]
[[Henryk Stażewski|Stażewski, Henryk]]
[[Alexander Stoddart|Stoddart, Alexander]]
[[Gilbert Stuart|Stuart, Gilbert]]
[[Gengoroh Tagame|Tagame, Gengoroh]]
[[Tang Da Wu]]
[[Alice Tangerini|Tangerini, Alice]]
[[Bruce Timm|Timm, Bruce]]
[[Turkey Tolson Tjupurrula|Tjupurrula, Turkey Tolson]]
[[Akira Toriyama|Toriyama Akira]]
[[Toyohara Kunichika]]
[[Philip Treacy|Treacy, Philip]]
[[Lise Tréhot|Tréhot, Lise]]
[[Toshiko Ueda|Ueda, Toshiko]]
[[Utagawa Toyoharu]]
[[William Utermohlen|Utermohlen, William]]
[[Willy Vandersteen|Vandersteen, Willy]]
[[Nina de Creeft Ward|Ward, Nina de Creeft]]
[[Agnes Weinrich|Weinrich, Agnes]]
[[Al Williamson|Williamson, Al]]
[[Kacey Wong|Wong, Kacey]]
[[Bernie Wrightson|Wrightson, Bernie]]
[[Xue Susu]]
[[Kanae Yamamoto (artist)|Yamamato Kanae]]
[[Ye Qianyu]]
[[Tomás Yepes|Yepes, Tomás]]
[[Mahonri Young|Young, Mahonri]]
[[Plácido Zuloaga|Zuloaga, Plácido]]
}}

</div>
</div>
<!--End Art level 3 GA subtopic-->
<!--Start Architecture level 3 GA subtopic-->
<div class="mw-collapsible">

===[[File:Square compasses.png|22px|left|link=|alt=]] Architecture===
<div class="wp-ga-topic-back">[[#Art and architecture|back]]</div>
<div class="mw-collapsible-content">

====Architecture====
{{#invoke:Good Articles|subsection|
[[Ammonia fuming]]
[[Architecture of Bedford Park]]
[[Architecture of Denmark]]
[[Architecture of Fremantle Prison]]
[[Architecture of Leeds]]
[[Architecture of Madagascar]]
[[Architecture of Norway]]
[[Architecture of Scotland]]
[[Architecture of Scotland in the Industrial Revolution]]
[[Architecture of Scotland in the Middle Ages]]
[[Architecture of Scotland in the prehistoric era]]
[[Architecture of Scotland in the Roman era]]
[[Architecture in early modern Scotland]]
[[Architecture in modern Scotland]]
[[Architecture of the Song dynasty]]
[[Architecture of Winchester College]]
[[Art Deco architecture of New York City]]
[[Art Nouveau architecture in Riga]]
[[British industrial architecture]]
[[Buildings and architecture of Bath]]
[[Castles in Great Britain and Ireland]]
[[Communitas (book)|''Communitas'' (book)]]
[[Dutch brick]]
[[Early skyscrapers]]
[[Fatimid architecture]]
[[Grade I listed buildings in Somerset]]
[[Horse rings in Portland, Oregon]]
[[Mathematics and architecture]]
[[Onion dome]]
[[Phallic architecture]]
[[Scottish castles]]
}}

====Architecture – Bridges and tunnels====
{{#invoke:Good Articles|subsection|
[[Alconétar Bridge]]
[[Ashland Mill Bridge]]
[[Barmouth Bridge]]
[[Benjamin G. Humphreys Bridge]]
[[Big Four Bridge]]
[[Blackledge River Railroad Bridge]]
[[Bull's Bridge]]
[[Bridge near Limyra]]
[[Datchet Bridge]]
[[Dukes Meadows Footbridge]]
[[Fort Steuben Bridge]]
[[Gallox Bridge, Dunster]]
[[Gateshead Millennium Bridge]]
[[Grand Street Bridge (Connecticut)]]
[[Grič Tunnel (Zagreb)]]
[[Hulme Arch Bridge]]
[[The Iron Bridge]]
[[New Harmony Toll Bridge]]
[[Nutty Narrows Bridge]]
[[Old Bridge, Pontypridd]]
[[Pulteney Bridge]]
[[Robert Parker Coffin Bridge]]
[[Samson Occom Bridge]]
[[Severn Railway Bridge]]
[[St Elmo Bridge]]
[[Tickle Cock Bridge]]
[[Weesperplein metro station]]
[[West Cornwall Covered Bridge]]
[[White House to Treasury Building tunnel]]
}}

====Architecture – Buildings====
{{#invoke:Good Articles|subsection|
[[1 Utama]]
[[34 Montagu Square, Marylebone]]
[[108 St Georges Terrace]]
[[111 Somerset]]
[[Agustín Ross Cultural Centre]]
[[Algo Centre Mall]]
[[Altes Stadthaus, Berlin]]
[[Altes Stadthaus, Bonn]]
[[Amber Room]]
[[The Angel, Islington]]
[[Auberge d'Italie]]
[[Aula Magna (Central University of Venezuela)]]
[[Bass Maltings, Sleaford]]
[[Bath Assembly Rooms]]
[[Baths of Zeuxippus]]
[[Battersea Town Hall]]
[[The Bear, Oxford]]
[[Bebenhausen Abbey]]
[[Beckford's Tower]]
[[Brighton Forum]]
[[Brighton Palace Pier]]
[[Bristol County Jail]]
[[Bristol Customshouse and Post Office]]
[[British Library]]
[[Brooke Street Pier]]
[[Bruton Dovecote]]
[[Castellania (Valletta)]]
[[Central Park (skyscraper)]]
[[Central Saint Giles]]
[[Chalke]]
[[Chester Rows]]
[[Cine City, Withington]]
[[Clal Center]]
[[Clarendon Shopping Centre]]
[[Clevedon Pier]]
[[Cleveland Pools]]
[[Clock Tower (Central University of Venezuela)]]
[[College of All Saints, Maidstone]]
[[Cork Courthouse, Anglesea Street]]
[[Council House, Perth]]
[[Coxton Tower]]
[[The Crescent, Taunton]]
[[Crystal Palace Dinosaurs]]
[[Cunard Building]]
[[De Akkermolen]]
[[Dolphinarium]]
[[Dovecot at Blackford Farm]]
[[Dowhill Castle]]
[[The Doughnut]]
[[Dunster Working Watermill]]
[[Édifice Price]]
[[Edinburgh Place Ferry Pier]]
[[The Exchange, Bristol]]
[[Forbidden City]]
[[Fyne Court]]
[[Garrick's Temple to Shakespeare]]
[[Gateway of India]]
[[The Golden Beam]]
[[Grand Palace]]
[[Gregorian Tower]]
[[Halden Prison]]
[[Halifax Central Library]]
[[Harmondsworth Great Barn]]
[[Harpy Tomb]]
[[Jahanpanah]]
[[Jeddah Tower]]
[[Kabul City Center]]
[[Khaplu Palace]]
[[King Alfred's Tower]]
[[Kirkcudbright Tolbooth]]
[[Kőbánya cellar system]]
[[Krak des Chevaliers]]
[[Layer Pyramid]]
[[Liverpool Town Hall]]
[[London Road Fire Station, Manchester]]
[[Lytham Pier]]
[[Mamilla Mall]]
[[Marine Parade Community Building]]
[[Masonic Hall, Taunton]]
[[MediaCityUK]]
[[Midnight Sun Mosque]]
[[Mundo Perdido, Tikal]]
[[Murrays' Mills]]
[[National Assembly Building of Slovenia]]
[[Naulakha Pavilion]]
[[New Brighton Tower]]
[[O'Connell Street]]
[[Old National Library Building]]
[[Oyasato-yakata]]
[[Pall Mall, London]]
[[Park Crescent, Brighton]]
[[Parliament Hill]]
[[Parliament House (Malta)]]
[[Parthenon Frieze]]
[[Pavillon de Flore]]
[[Plan of Saint Gall]]
[[Polonnaruwa Vatadage]]
[[Pont du Gard]]
[[Port of Liverpool Building]]
[[Powis Castle]]
[[Procuratie]]
[[Pyramid of Khentkaus I]]
[[Pyramid of Userkaf]]
[[Qal'at al-Bahrain]]
[[Queen's Pier]]
[[Regency Square, Brighton]]
[[Rhyl Pier]]
[[Robot Building]]
[[Rochdale Town Hall]]
[[Roman Baths (Bath)]]
[[Royal Crescent]]
[[Royal Oak, Frindsbury]]
[[St Anne's Pier]]
[[St Mark's Campanile]]
[[Scotiabank Saddledome]]
[[Senate House, London]]
[[Senedd building]]
[[SIS Building]]
[[Sky Pool, London]]
[[Southend Pier]]
[[Southport Pier]]
[[Stanley Industrial Alliance Stage]]
[[Stembridge Mill, High Ham]]
[[Stoke sub Hamdon Priory]]
[[Stowe Gardens]]
[[Tala tank]]
[[Tokyo Tower]]
[[Tomb of Aegisthus]]
[[Tomb of Tutankhamun]]
[[Trellick Tower]]
[[Via della Conciliazione]]
[[Victoria Rooms, Bristol]]
[[Wales Millennium Centre]]
[[Watermill at Opwetten]]
[[Westminster Abbey]]
[[West Pennard Court Barn]]
[[West Pier]]
[[Wignacourt Arch]]
[[Yarn Market, Dunster]]
[[Yue Hwa Building]]
[[Zytglogge]]
}}

=====Architecture – Buildings of the United States=====
{{#invoke:Good Articles|subsection|
[[350 North Orleans]]
[[360 Newbury Street]]
[[370 Jay Street]]
[[500 Club]]
[[515 North Washington Street]]
[[801 Grand]]
[[901 New York Avenue]]
[[Albany City Hall]]
[[Alcatraz Federal Penitentiary]]
[[Allenville Mill Storehouse]]
[[Ambler's Texaco Gas Station]]
[[American Bank Note Company Printing Plant]]
[[American Thermos Bottle Company Laurel Hill Plant]]
[[Arrivé]]
[[Art's Auto]]
[[Astronomical Observatory (University of Illinois Urbana-Champaign)]]
[[AT&T Plaza]]
[[Austin, Nichols and Company Warehouse]]
[[Ballard Carnegie Library]]
[[Bellevue City Hall]]
[[Benevolent and Protective Order of Elks, Lodge Number 878]]
[[Blackford County Courthouse]]
[[Blackstone Library]]
[[Block 37]]
[[Broadway Hollywood Building]]
[[Brooklyn Army Terminal]]
[[The Brooklyn Tower]]
[[Burnham Pavilions]]
[[Caesars Palace]]
[[Capital Garage]]
[[Castleton Square]]
[[Centre Square (building)|Centre Square]]
[[Chana School]]
[[Charlestowne Mall]]
[[Chase Promenade]]
[[Chicago Spire]]
[[Chiming Fountain]]
[[Citygarden]]
[[Club Harlem]]
[[Colonial Plaza]]
[[Comcast Center]]
[[Commerce Square]]
[[Constitution Center (Washington, D.C.)]]
[[Crystal Heights]]
[[Daniel S. Schanck Observatory]]
[[Delta County Courthouse]]
[[Demonet Building]]
[[Domino Sugar Refinery]]
[[Dumas Brothel]]
[[Eliel Saarinen's Tribune Tower design]]
[[Ely Hall]]
[[Entranceway at Main Street at Roycroft Boulevard]]
[[Entranceways at Main Street at Lamarck Drive and Smallwood Drive]]
[[Federal Reserve Bank Building (Seattle)]]
[[Fifth Ward Wardroom]]
[[Fire Station No. 4 (Pawtucket, Rhode Island)]]
[[Fire Station No. 23 (Los Angeles, California)]]
[[First National Bank Tower]]
[[First Ward Wardroom]]
[[Forest Fair Village]]
[[Franklin Center (Chicago)]]
[[Freedman's Bank Building]]
[[Frost Bank Tower]]
[[Gaviidae Common]]
[[Geology Hall, New Brunswick, New Jersey]]
[[Gerald Ratner Athletics Center]]
[[Gould Memorial Library]]
[[Gowanus Batcave]]
[[Grand Prospect Hall]]
[[Great Lakes Crossing Outlets]]
[[Harold Washington Cultural Center]]
[[Hartford City Courthouse Square Historic District]]
[[Hearst Castle]]
[[Herron Gymnasium]]
[[Hillsboro Civic Center]]
[[Historic Michigan Boulevard District]]
[[Historic Presbyterian Community Center (Madison, Nebraska)]]
[[History of Cincinnati Union Terminal]]
[[Holden Block]]
[[Hopewell High School Complex]]
[[Hudson County Courthouse]]
[[Huntington Bank Stadium]]
[[IBM Building, Honolulu]]
[[Indiana Statehouse]]
[[Industry City]]
[[Joffrey Tower]]
[[Kickstarter headquarters]]
[[Kings Plaza]]
[[Kirkbride Plan]]
[[Lahaina Gateway]]
[[Lansing Mall]]
[[Lathrop House (Vassar College)]]
[[Leiter House]]
[[LeVeque Tower]]
[[Los Arcos Mall]]
[[Macon Library]]
[[Main Quad (Stanford University)]]
[[Malloch Building]]
[[Mark O. Hatfield Library]]
[[Marquette Building (Chicago)]]
[[Marshall Field and Company Building]]
[[McAllister Tower Apartments]]
[[McDonald's Chicago Flagship]]
[[Meridian Mall]]
[[Merle Hay Mall]]
[[Minneapolis City Center]]
[[Minnesota State Capitol]]
[[Murano (skyscraper)]]
[[New York and Long Island Coignet Stone Company Building]]
[[New York Court of Appeals Building]]
[[Nokomis Library]]
[[North Transfer Station]]
[[Old Bacon Academy]]
[[One Meridian Plaza]]
[[One Rincon Hill]]
[[One South Broad]]
[[Oregon Civic Justice Center]]
[[Oregon Public Library]]
[[O Street Market]]
[[Pacific Tower (Seattle)]]
[[Peachtree Arcade]]
[[Pepsi-Cola sign]]
[[Petersen Rock Garden]]
[[Petrillo Music Shell]]
[[Phillips Exeter Academy Library]]
[[Portland City Hall (Oregon)]]
[[Presidio of Santa Barbara]]
[[Pui Tak Center]]
[[The Residences at The Ritz-Carlton (Philadelphia)]]
[[Roanoke Building]]
[[Rohm and Haas Corporate Headquarters]]
[[Rolling Acres Mall]]
[[Rookery Building]]
[[Southworth Library (Dartmouth, Massachusetts)]]
[[The St. James]]
[[Schulze Baking Company Plant]]
[[Seattle Convention Center]]
[[Seattle Times Building]]
[[Seeley G. Mudd Chemistry Building]]
[[Sixteenth Street Historic District]]
[[Southdale Center]]
[[Strang School District No. 36]]
[[Students' Building (Vassar College)]]
[[Sunset Park Material Recovery Facility]]
[[Swifton Center]]
[[Sycamore Historic District]]
[[Toyota Center]]
[[Tri-City Pavilions]]
[[Tri-County Mall]]
[[Trylon Cinema]]
[[TWA Flight Center]]
[[Unisphere]]
[[United States Capitol cornerstone laying]]
[[United States Institute of Peace Headquarters]]
[[United States National Bank Building]]
[[University Mall (Little Rock, Arkansas)]]
[[The Valley Library]]
[[WaHu Student Apartments]]
[[Waller Hall]]
[[Wayne Lyman Morse United States Courthouse]]
[[Wayzata Bay Center]]
[[Wells Fargo Building (Philadelphia)]]
[[Westinghouse Air Brake Company General Office Building]]
[[Wieting Opera House]]
[[William Ulmer Brewery]]
[[Williamsburgh Savings Bank Building (175 Broadway)]]
[[Williamsburgh Savings Bank Tower]]
[[Willow Grove Park Mall]]
[[Wirgman Building]]
[[Woodstock Library]]
[[World's littlest skyscraper]]
[[Wrigley Square]]
[[Yale Union Laundry Building]]
}}

======Architecture – Buildings of Manhattan======
{{#invoke:Good Articles|subsection|
[[1 Broadway]]
[[1 Hanover Square]]
[[1 Wall Street]]
[[1 Wall Street Court]]
[[2 Broadway]]
[[2 Columbus Circle]]
[[2 Park Avenue]]
[[3 East 57th Street]]
[[3 Times Square]]
[[4 Park Avenue]]
[[4 Times Square]]
[[5 Beekman Street]]
[[5 Columbus Circle]]
[[5 Times Square]]
[[14 Wall Street]]
[[18 East 50th Street]]
[[20 Exchange Place]]
[[26 Broadway]]
[[28 Liberty Street]]
[[30 Rockefeller Plaza]]
[[30 West 44th Street]]
[[32 Avenue of the Americas]]
[[32 Old Slip]]
[[40 Wall Street]]
[[44 Union Square]]
[[48 Wall Street]]
[[49 Chambers]]
[[53W53]]
[[56 Beaver Street]]
[[60 Hudson Street]]
[[60 Wall Street]]
[[65 Broadway]]
[[70 Pine Street]]
[[90 West Street]]
[[108 Leonard]]
[[110 East 42nd Street]]
[[111 Eighth Avenue]]
[[111 West 57th Street]]
[[140 Broadway]]
[[150 Nassau Street]]
[[165 West 57th Street]]
[[195 Broadway]]
[[200 Madison Avenue]]
[[218 West 57th Street]]
[[224 West 57th Street]]
[[229 West 43rd Street]]
[[270 Park Avenue (1960–2021)]]
[[275 Madison Avenue]]
[[280 Broadway]]
[[330 West 42nd Street]]
[[383 Madison Avenue]]
[[390 Fifth Avenue]]
[[400 Madison Avenue]]
[[452 Fifth Avenue]]
[[488 Madison Avenue]]
[[500 Fifth Avenue]]
[[500 Park Avenue]]
[[550 Madison Avenue]]
[[590 Madison Avenue]]
[[608 Fifth Avenue]]
[[647 Fifth Avenue]]
[[660 Fifth Avenue]]
[[689 Fifth Avenue]]
[[712 Fifth Avenue]]
[[750 Seventh Avenue]]
[[1271 Avenue of the Americas]]
[[1501 Broadway]]
[[1540 Broadway]]
[[1552 Broadway]]
[[1585 Broadway]]
[[American Bank Note Company Building]]
[[American Fine Arts Society]]
[[American Radiator Building]]
[[American Stock Exchange Building]]
[[American Surety Building]]
[[Amster Yard]]
[[Apple Bank Building]]
[[Axa Equitable Center]]
[[Bank of America Tower (Manhattan)]]
[[Barclay–Vesey Building]]
[[Bennett Building (New York City)]]
[[Bowling Green Offices Building]]
[[British Empire Building]]
[[Broad Exchange Building]]
[[Bryant Park Studios]]
[[Bush Tower]]
[[B. Altman and Company Building]]
[[Candler Building (New York City)]]
[[Carnegie Hall Tower]]
[[Cartier Building]]
[[CBS Building]]
[[Central Park Tower]]
[[Chamber of Commerce Building (Manhattan)]]
[[Chanin Building]]
[[Charles Scribner's Sons Building]]
[[Chrysler Building]]
[[Church Missions House]]
[[Citigroup Center]]
[[City Investing Building]]
[[CitySpire]]
[[Consolidated Edison Building]]
[[Corbin Building]]
[[Coty Building]]
[[Cunard Building (New York City)]]
[[Daily News Building]]
[[Deutsche Bank Center]]
[[Downtown Athletic Club]]
[[Empire Building (Manhattan)]]
[[Empire State Building]]
[[Engineering Societies' Building]]
[[Engineers' Club Building]]
[[Equitable Building (Manhattan)]]
[[Equitable Life Building (Manhattan)]]
[[Federal Reserve Bank of New York Building]]
[[Ford Foundation Center for Social Justice]]
[[Fred F. French Building]]
[[Fuller Building]]
[[General Electric Building]]
[[General Motors Building (Manhattan)|General Motors Building]]
[[Gillender Building]]
[[Grand Central Terminal]]
[[Graybar Building]]
[[Greenwich Savings Bank Building]]
[[Hearst Tower (Manhattan)]]
[[Helmsley Building]]
[[History of Grand Central Terminal]]
[[Home Life Building]]
[[Hudson Yards (development)]]
[[International Building (Rockefeller Center)]]
[[IRT Powerhouse]]
[[La Maison Francaise (Rockefeller Center)]]
[[Lever House]]
[[Liberty Tower (Manhattan)]]
[[Little Island at Pier 55]]
[[Lord & Taylor Building]]
[[Manhattan Municipal Building]]
[[Manufacturers Trust Company Building]]
[[MetLife Building]]
[[Metropolitan Life Insurance Company Tower]]
[[Metropolitan Tower (Manhattan)|Metropolitan Tower]]
[[Morse Building]]
[[Mutual Reserve Building]]
[[New York Life Building]]
[[New York Public Library Main Branch]]
[[The New York Times Building]]
[[New York Times Building (41 Park Row)]]
[[New York Tribune Building]]
[[New York World Building]]
[[The Normandy]]
[[Olympic Tower]]
[[One57]]
[[One Astor Plaza]]
[[One Times Square]]
[[One Vanderbilt]]
[[One World Trade Center]]
[[Ottendorfer Public Library and Stuyvesant Polyclinic Hospital]]
[[Park Row Building]]
[[Pershing Square Building]]
[[Potter Building]]
[[Rockefeller Center]]
[[Rodin Studios]]
[[Saks Fifth Avenue flagship store]]
[[Scribner Building]]
[[Smalls Paradise]]
[[Socony–Mobil Building]]
[[Solow Building]]
[[Stavros Niarchos Foundation Library]]
[[Tiffany and Company Building]]
[[Times Square Tower]]
[[Trump Tower]]
[[United Nations General Assembly Building]]
[[Village East by Angelika]]
[[Western Union Telegraph Building]]
[[Whitehall Building]]
[[Woolworth Building]]
[[World Trade Center (1973–2001)]]
[[World Trade Center (2001–present)]]
}}

====Architecture – Forts and fortifications====
{{See|Wikipedia:Good articles/Warfare#Fortifications and military installations|Wikipedia:Good articles/Warfare#Castles}}

====Architecture – Hotels and inns====
{{#invoke:Good Articles|subsection|
[[The Beverly Hills Hotel]]
[[The Blackstone Hotel]]
[[Crowne Plaza Times Square Manhattan]]
[[Desert Inn]]
[[The Dorchester]]
[[DoubleTree by Hilton Hotel Metropolitan New York City]]
[[The George Hotel, Crawley]]
[[Hilton Washington DC National Mall]]
[[Hôtel d'Alluye]]
[[Hôtel Ritz Paris]]
[[Hotel Valley Ho]]
[[The Knickerbocker Hotel]]
[[Landmark (hotel and casino)]]
[[Lotte New York Palace Hotel]]
[[Manila Hotel]]
[[Millennium Hilton New York One UN Plaza]]
[[Millennium Times Square New York]]
[[New York Marriott Marquis]]
[[Palace Hotel, Perth]]
[[Paramount Hotel]]
[[Pikes Hotel]]
[[Plaza Hotel]]
[[The Ritz Hotel, London]]
[[Royal Albion Hotel]]
[[Ryugyong Hotel]]
[[Sands Hotel and Casino]]
[[Sauganash Hotel]]
[[Shamrock Hotel]]
[[Trump International Hotel and Tower (New York City)]]
[[U-Drop Inn]]
[[Virgin Hotels Chicago]]
[[W New York Union Square]]
[[Waldorf Astoria New York]]
[[Waldorf-Astoria (1893–1929)]]
[[Watson's Hotel]]
}}

====Architecture – Houses and residences====
{{#invoke:Good Articles|subsection|
[[5 West 54th Street]]
[[7 West 54th Street]]
[[10 West 56th Street]]
[[11 West 54th Street]]
[[12 East 53rd Street]]
[[13 and 15 West 54th Street]]
[[19 East 54th Street]]
[[23 Beekman Place]]
[[30 West 56th Street]]
[[219 East 49th Street]]
[[220 Central Park South]]
[[240 Central Park South]]
[[432 Park Avenue]]
[[The Abbey, Sutton Courtenay]]
[[Acors Barns House]]
[[Adlington Hall]]
[[Alatskivi Castle]]
[[Althorp]]
[[Alwyn Court]]
[[American Gothic House]]
[[Ashlawn]]
[[Ashton Court]]
[[Avery House (Griswold, Connecticut)]]
[[Back-to-back house]]
[[Barrington Court]]
[[Beaumont House]]
[[Beaux-Arts Apartments]]
[[Bedford Park, London]]
[[Beechwood (Vanderlip mansion)]]
[[Benjamin Church House (Bristol, Rhode Island)]]
[[Benjamin Ogle Tayloe House]]
[[Bicknell–Armington Lightning Splitter House]]
[[Blair House]]
[[Blaise Castle Estate]]
[[Boughton Monchelsea Place]]
[[Brislington House]]
[[Camak House]]
[[Cannons (house)]]
[[Canterbury Castle (Portland, Oregon)]]
[[Capesthorne Hall]]
[[Carpenter House (Norwich, Connecticut)]]
[[Casa de Estudillo]]
[[The Century (apartment building)]]
[[Charles Payne House]]
[[Cholmondeley Castle]]
[[Churche's Mansion]]
[[Clevedon Court]]
[[Codman Carriage House and Stable]]
[[Coleridge Cottage]]
[[Colross]]
[[Craigiehall]]
[[Crewe Hall]]
[[Cushing House]]
[[Davison House]]
[[Dowse Sod House]]
[[Duncraig Castle]]
[[Dunrobin Castle]]
[[Dyrham Park]]
[[Eaton Hall, Cheshire]]
[[Ellwood House]]
[[Ernest Hemingway House]]
[[Estate houses in Scotland]]
[[Felix M. Warburg House]]
[[Forglen House]]
[[Fort Belvedere, Surrey]]
[[Foster–Payne House]]
[[Fraser Mansion]]
[[Fuller Houses]]
[[Gainsborough Studios (Manhattan)]]
[[Gawsworth Old Hall]]
[[Heller House]]
[[Highgrove House, Eastcote]]
[[Hillingdon House]]
[[Hilston Park]]
[[Hollensbury Spite House]]
[[House at 130 Mohegan Avenue]]
[[Housing in Scotland]]
[[Ince Blundell Hall]]
[[Inchdrewer Castle]]
[[Indiana Governor's Residence]]
[[James B. Duke House]]
[[James G. Blaine Mansion]]
[[Jewett House]]
[[John F. Adams House]]
[[Joseph F. Glidden House]]
[[Kenwood, St George's Hill]]
[[King John's Hunting Lodge, Axbridge]]
[[Kingston Lacy]]
[[La Pausa]]
[[Leigh Court]]
[[Lemmons]]
[[Lescaze House]]
[[Linton Park]]
[[Linwood House]]
[[Lohn Estate]]
[[Luscombe Castle]]
[[Lyme Park]]
[[Lytes Cary]]
[[The Majestic (apartment building)]]
[[Manor House, Sleaford]]
[[Master Apartments]]
[[Mathew H. Ritchey House]]
[[Medieval Merchant's House]]
[[Milam Residence]]
[[Mission House (Stockbridge, Massachusetts)]]
[[Montacute House]]
[[Nailsea Court]]
[[Nettlecombe Court]]
[[Newton House, Llandeilo]]
[[North Shore Towers]]
[[Old House of Keys]]
[[Old Stone House (Washington, D.C.)]]
[[Ordsall Hall]]
[[The Osborne]]
[[Palais Rohan, Strasbourg]]
[[Palazzo Rusticucci-Accoramboni]]
[[Payne Whitney House]]
[[Penrhyn Castle]]
[[Plas Mawr]]
[[Portland Flats]]
[[Potter–Collyer House]]
[[Prior Park]]
[[Prior Park Landscape Garden]]
[[Pruitt–Igoe]]
[[Rancho Camulos]]
[[Rideau Cottage]]
[[Ritz Tower]]
[[Rockefeller Apartments]]
[[Rockefeller Guest House]]
[[Rode Hall]]
[[Rodmarton Manor]]
[[Roger Mowry Tavern]]
[[Rusco Tower]]
[[St Catherine's Court]]
[[The San Remo]]
[[Sheldon Manor]]
[[Somerhill House]]
[[South Stoneham House]]
[[Southworth House (Cleveland, Ohio)]]
[[Sri Temasek]]
[[Stewart's Castle]]
[[Ston Easton Park]]
[[Sutton Court]]
[[Swakeleys House]]
[[Tabley House]]
[[Taliesin (studio)]]
[[Tintinhull Garden]]
[[Treasurer's House, Martock]]
[[The Tribunal, Glastonbury]]
[[Tyntesfield]]
[[Vanderbilt Triple Palace]]
[[Villard Houses]]
[[Virginia House]]
[[Vorontsov Palace (Alupka)]]
[[Wappocomo (Romney, West Virginia)]]
[[Warrick House (Meadow Grove, Nebraska)]]
[[Westholme House]]
[[William H. Moore House]]
[[Wilson-Wodrow-Mytinger House]]
[[Winslow Ames House]]
[[Woodland House]]
[[Wyntoon]]
}}

====Architecture – Lighthouses====
{{#invoke:Good Articles|subsection|
[[Avery Point Light]]
[[Black Rock Harbor Light]]
[[Bridgeport Harbor Light]]
[[Cape Moreton Light]]
[[Chester Rock Light]]
[[Essex Reef Light]]
[[Europa Point Lighthouse]]
[[Falkner Island Light]]
[[Great Captain Island Light]]
[[Green Bay Harbor Entrance Light]]
[[Greens Ledge Light]]
[[Kõpu Lighthouse]]
[[Lynde Point Light]]
[[Mystic Seaport Light]]
[[Norah Head Light]]
[[Point Stephens Light]]
}}

====Architecture – Memorials and monuments====
{{See|Wikipedia:Good articles/Warfare#Military museums and memorials}}
{{#invoke:Good Articles|subsection|
''[[Aboriginal Memorial]]''
[[Civil War Memorial (Sycamore, Illinois)]]
[[Civil War Memorial (Savannah, Georgia)]]
[[Confederate Memorial (Romney, West Virginia)]]
[[Collyer Monument]]
[[Dorchester Heights Monument]]
[[Dr. Samuel Mitchel Smith and Sons Memorial Fountain]]
[[Duffield Memorial]]
[[Equestrian statue of Ambrose Burnside]]
[[Frank E. Beach Memorial Fountain]]
[[George Gordon Meade Memorial]]
[[Glorieta de las mujeres que luchan]]
[[Grey's Monument]]
[[Groton Monument]]
[[Gwinnett Environmental & Heritage Center]]
[[Hokitika Clock Tower]]
[[Indio Comahue Monument]]
[[Israel Putnam Monument]]
[[James Oglethorpe Monument]]
[[Littlefield Fountain]]
[[Memorial to Victims of Violence in Mexico]]
[[Nathanael Greene Monument]]
[[National Police Memorial (United Kingdom)|National Police Memorial]]
[[Penshaw Monument]]
[[Peter Muhlenberg Memorial]]
[[The Pioneer Mother Memorial|''The Pioneer Mother Memorial'']]
[[Samuel Hahnemann Monument]]
[[Sir Bevil Grenville's Monument]]
[[Statue of Israel Putnam]]
[[Statue of John Carroll]]
[[Stephenson Grand Army of the Republic Memorial]]
[[Taras Shevchenko Memorial]]
[[Theodore Roosevelt Memorial (Portland, Oregon)]]
[[Washington Monument]]
[[Wellington Monument, Somerset]]
[[Wind phone]]
[[World War I Memorial (East Providence, Rhode Island)]]
[[Yad Kennedy]]
}}

====Architecture – Museums and galleries====
{{#invoke:Good Articles|subsection|
[[Arnolfini]]
[[Arts Club of Chicago]]
[[Baltic Centre for Contemporary Art]]
[[Beit Al Quran]]
[[Boeing Galleries]]
[[British Engineerium]]
[[British Library Philatelic Collections]]
[[Churchill War Rooms]]
[[Clinton Presidential Center]]
[[Crane and Company Old Stone Mill Rag Room]]
[[Croatian Natural History Museum]]
[[Cummer Museum of Art and Gardens]]
[[Currency Building]]
[[DakshinaChitra]]
[[Debbane Palace]]
[[DuSable Black History Museum and Education Center]]
[[Floating Clouds (artwork)|''Floating Clouds'' (artwork)]]
[[Garbage Museum]]
[[Getty Center]]
[[Getty Conservation Institute]]
[[Getty Foundation|Getty Foundation]]
[[Getty Research Institute]]
[[Getty Villa]]
[[Glenn & Viola Walters Cultural Arts Center]]
[[Glenstone]]
[[Hall of Fame for Great Americans]]
[[Hallie Ford Museum of Art]]
[[Imperial War Museum]]
[[Imperial War Museum Duxford]]
[[Imperial War Museum North]]
[[Indianapolis Museum of Art]]
[[J. Paul Getty Trust]]
[[John F. Kennedy Presidential Library and Museum]]
[[Louvre]]
[[Louvre Abu Dhabi]]
[[Madame Tussauds Hong Kong]]
[[Museum de Oude Wolden]]
[[Museum of Contemporary Art Australia]]
[[Museum of Contemporary Art Chicago]]
[[Museum of Socialist Art]]
[[National Gallery]]
[[National Museum of African Art]]
[[Old Korean Legation Museum]]
[[Old Melbourne Gaol]]
[[Palanga Amber Museum]]
[[Pearl Harbor Aviation Museum]]
[[Ronald Reagan Presidential Library]]
[[SeaCity Museum]]
[[The Precious Legacy]]
[[Vietnam National Museum of History]]
[[Westonzoyland Pumping Station Museum]]
[[York Museum Gardens]]
}}

====Architecture – Religious====
{{#invoke:Good Articles|subsection|
[[Abbey Mills Mosque]]
[[The Abbot's Fish House, Meare]]
[[Akhtala Monastery]]
[[Al-Aqsa Mosque]]
[[Al-Azhar Mosque]]
[[Al-Masjid an-Nabawi]]
[[Alchi Monastery]]
[[All Saints Church, Patcham]]
[[All Saints' Church, Runcorn]]
[[All Saints' Church, Shuart]]
[[All Saints' Church, Southampton]]
[[Anshei Israel Synagogue]]
[[Architecture of the medieval cathedrals of England]]
[[Armenian Monastic Ensembles of Iran]]
[[Arunachalesvara Temple]]
[[Ascension Cathedral (Veliko Tarnovo)]]
[[Baclayon Church]]
[[Badami cave temples]]
[[Badrinath Temple]]
[[Badshahi Mosque]]
[[Bath Abbey]]
[[Beiyue Temple]]
[[Bell Tower (University of Portland)]]
[[Benjaminville Friends Meeting House and Burial Ground]]
[[Bethesda Methodist Chapel, Hanley]]
[[Bishop's Palace, Wells]]
[[Bristol Cathedral]]
[[Brown Memorial Presbyterian Church]]
[[Buhl Altarpiece]]
[[Canton Synagogue]]
[[Capel Lligwy]]
[[Catedral de Nuestra Señora de Guadalupe]]
[[Cathedral of Ani]]
[[Cathedral of St. John the Divine]]
[[Cathedral of the Immaculate Conception (Hong Kong)]]
[[Chausath Yogini Temple, Mitaoli]]
[[Chau Say Tevoda]]
[[Chester Cathedral]]
[[Christ Church, Newton]]
[[Christ Episcopal Church (Waltham, Massachusetts)]]
[[Church Administration Building]]
[[Church architecture in Scotland]]
[[Church of Christ Pantocrator, Nesebar]]
[[The Church of Jesus Christ of Latter-day Saints in Tonga]]
[[Church of Saint Oswald, King and Martyr, Oswaldkirk]]
[[Church of St Demetrius, Patalenitsa]]
[[Church of St George, Kyustendil]]
[[Church of St John the Baptist, Asenovgrad]]
[[Church of St Nicholas, Sapareva Banya]]
[[Church of St Peter, Berende]]
[[Church of the Holy Mother of God, Asen's Fortress]]
[[Church of the Holy Mother of God, Donja Kamenica]]
[[Cleeve Abbey]]
[[Cullen Old Church]]
[[Dalby Church]]
[[Dunster Butter Cross]]
[[Etchmiadzin Cathedral]]
[[Evans Memorial Chapel]]
[[First Presbyterian Church of Newtown]]
[[Foguang Temple]]
[[Ganesha Temple, Morgaon]]
[[Ganting Grand Mosque]]
[[Garde Church]]
[[Ghazanchetsots Cathedral]]
[[Girih]]
[[Gisborough Priory]]
[[Glastonbury Abbey]]
[[Great Mosque of Gaza]]
[[Holy Rosary Cathedral (Vancouver)]]
[[Hurva Synagogue]]
[[Immaculate Conception Catholic Church (Celina, Ohio)]]
[[Jama Masjid, Delhi]]
[[Jokhang]]
[[Kandariya Mahadeva Temple]]
[[Kataragama temple]]
[[Kek Lok Si]]
[[Kirkpatrick Chapel]]
[[Knesset Eliyahoo]]
[[Kodandarama Temple, Vontimitta]]
[[Lacock Abbey]]
[[Laie Hawaii Temple]]
[[Larabanga Mosque]]
[[Lärbro Church]]
[[Leicester Abbey]]
[[Liverpool Metropolitan Cathedral]]
[[Llandaff Cathedral]]
[[Loboc Church]]
[[Lund Cathedral]]
[[Lye Church]]
[[Mahamuni Buddha Temple]]
[[Malé Friday Mosque]]
[[Maribojoc Church]]
[[Masrur Temples]]
[[Mexico City Metropolitan Cathedral]]
[[Mezhyhirya Monastery]]
[[Mount St. Peter Church]]
[[Muchelney Abbey]]
[[Munneswaram temple]]
[[Oakland Buddha]]
[[Old Church of St Gwenllwyfo, Llanwenllwyfo]]
[[Old St Paul's Cathedral]]
[[Our Lady Star of the Sea and St Winefride, Amlwch]]
[[Our Lady of Pompeii Church (Manhattan)]]
[[Park51]]
[[Parashurameshvara Temple]]
[[Poh Ern Shih Temple]]
[[Pohick Church]]
[[The Priest's House, Muchelney]]
[[Princeton University Chapel]]
[[Punakha Dzong]]
[[Pundarikakshan Perumal Temple]]
[[Riverside Church]]
[[San Giacomo Scossacavalli]]
[[San Sebastian Church (Manila)]]
[[Saint-Louis-du-Louvre]]
[[St Andrew's Church, Chew Stoke]]
[[St Beuno's Church, Aberffraw]]
[[St Beuno's Church, Trefdraeth]]
[[St Caffo's Church, Llangaffo]]
[[St Caian's Church, Tregaian]]
[[St Ceidio's Church, Rhodogeidio]]
[[St Ceinwen's Church, Cerrigceinwen]]
[[St Chad's Church, Poulton-le-Fylde]]
[[St Cristiolus's Church, Llangristiolus]]
[[St Cwyllog's Church, Llangwyllog]]
[[St Cynfarwy's Church, Llechgynfarwy]]
[[St Deiniol's Church, Llanddaniel Fab]]
[[St Dona's Church, Llanddona]]
[[St Edern's Church, Bodedern]]
[[St Edwen's Church, Llanedwen]]
[[St Eleth's Church, Amlwch]]
[[St Enghenedl's Church, Llanynghenedl]]
[[St Eugrad's Church, Llaneugrad]]
[[St Ffinan's Church, Llanffinan]]
[[St Fflewin's Church, Llanfflewin]]
[[St Gallgo's Church, Llanallgo]]
[[St George's Church, Trotton]]
[[St Gwenllwyfo's Church]]
[[St Iestyn's Church, Llaniestyn]]
[[St James' Church, Stretham]]
[[St. James Church (Queens)]]
[[St John the Baptist Church, Reid]]
[[St John's, Ashfield]]
[[St John's Church, Manchester]]
[[St. John's Orphanage]]
[[St Joseph's Convent, Taunton]]
[[St. Joseph's Church, Semarang]]
[[St Julian's Church, Norwich]]
[[St Lawrence's Church, Mereworth]]
[[Saint Leonard Catholic Church (Madison, Nebraska)]]
[[St Llibio's Church, Llanllibio]]
[[St Margaret's Church, Aberlour]]
[[St Margaret's Church, Ifield]]
[[St Mark's Basilica]]
[[St. Martin, Idstein]]
[[St Mary Redcliffe]]
[[St Mary's Church, Acton]]
[[St. Mary's Church (Albany, New York)]]
[[St Mary's Church, Astbury]]
[[St Mary's Church, Bodewryd]]
[[St Mary's Church, Chesham]]
[[St Mary's Church, Llanfair Mathafarn Eithaf]]
[[St Mary's Church, Llanfair-yn-y-Cwmwd]]
[[St Mary's Church, Llanfair-yng-Nghornwy]]
[[St Mary's Church, Nantwich]]
[[St Mary's Church, Nether Alderley]]
[[St Mary's Church, Pentraeth]]
[[St Mary's Church, Reculver]]
[[St Mary's Church, Rhodogeidio]]
[[St Mary's Church, Rolleston on Dove]]
[[St Mary's Church, Tal-y-llyn]]
[[St. Mary's-in-Tuxedo Episcopal Church]]
[[St Michael's Church, Llanfihangel Ysgeifiog]]
[[St Mihangel's Church, Llanfihangel yn Nhowyn]]
[[St Nicholas Church, Chiswick]]
[[St Nidan's Church, Llanidan]]
[[St Pabo's Church, Llanbabo]]
[[St. Patrick's Cathedral (Midtown Manhattan)]]
[[St Peirio's Church, Rhosbeirio]]
[[Saint Peter of Alcantara Parish Church (Pakil)]]
[[St Peter's Church, Llanbedrgoch]]
[[St Peter's Church, Sudbury]]
[[St. Peter's Church (Queenstown, Maryland)]]
[[St Peter's Roman Catholic Church, Buckie]]
[[St Peulan's Church, Llanbeulan]]
[[St Rufus Church]]
[[St Thomas the Martyr's Church, Oxford]]
[[St Twrog's Church, Bodwrog]]
[[St Tyfrydog's Church, Llandyfrydog]]
[[Sera Monastery]]
[[Shwezigon Pagoda]]
[[Shanhua Temple]]
[[Shrine of the Immaculate Conception]]
[[Stained glass in Liverpool Cathedral]]
[[Stånga Church]]
[[Storkyrkan]]
[[Surb Karapet Monastery]]
[[Sunol Water Temple]]
[[Swaminarayan Akshardham (Delhi)]]
[[Taunton Unitarian Chapel]]
[[Tawang Monastery]]
[[Temple of Garni]]
[[Ten Thousand Buddhas Monastery]]
[[Timoleague Friary]]
[[Tịnh Xá Trung Tâm]]
[[Tomb of Safdar Jang]]
[[Towson United Methodist Church]]
[[Trinity Episcopal Church (Washington, D.C.)]]
[[Unionskirche, Idstein]]
[[Unitarian Universalist Church of Arlington]]
[[Upper Brook Street Chapel, Manchester]]
[[Uppsala Cathedral]]
[[Vä Church]]
[[Varagavank]]
[[Växjö Cathedral]]
[[Vazelon Monastery]]
[[Vimala Temple]]
[[Visby Cathedral]]
[[Woodspring Priory]]
[[Zagreb Synagogue]]
[[Zhenguo Temple]]
}}

====Architecture – Theatres====
{{#invoke:Good Articles|subsection|
[[5th Avenue Theatre]]
[[Al Hirschfeld Theatre]]
[[Ambassador Theatre (New York City)]]
[[American Airlines Theatre]]
[[August Wilson Theatre]]
[[Baralt Theatre]]
[[Beacon Theatre (New York City)]]
[[Belasco Theatre]]
[[Bernard B. Jacobs Theatre]]
[[Booth Theatre]]
[[Broadhurst Theatre]]
[[Broadway Theatre (53rd Street)]]
[[Chicago Theatre]]
[[Clinton Street Theater]]
[[Ed Sullivan Theater]]
[[Embassy Theatre (New York City)]]
[[Ethel Barrymore Theatre]]
[[Eugene O'Neill Theatre]]
[[Gerald Schoenfeld Theatre]]
[[Gershwin Theatre]]
[[Hayes Theater]]
[[Hudson Theatre]]
[[Imperial Theatre]]
[[James Earl Jones Theatre]]
[[John Golden Theatre]]
[[Lena Horne Theatre]]
[[Liberty Theatre]]
[[Longacre Theatre]]
[[Lunt-Fontanne Theatre]]
[[Lyceum Theatre (Broadway)]]
[[Lyric Theatre (New York City, 1998)]]
[[Majestic Theatre (Broadway)]]
[[Mark Hellinger Theatre]]
[[Marquis Theatre]]
[[Merle Reskin Theatre]]
[[Minskoff Theatre]]
[[Music Box Theatre]]
[[Nederlander Theatre]]
[[Neil Simon Theatre]]
[[Oregon Theatre]]
[[Palace Theatre (New York City)]]
[[Paramount Theatre (Atlanta)]]
[[Princess Theatre (Edmonton)]]
[[Radio City Music Hall]]
[[Ramsdell Theatre]]
[[Richard Rodgers Theatre]]
[[Riverview Theater]]
[[RKO Keith's Theater (Flushing, Queens)]]
[[Roseland Theater]]
[[Rosendale Theatre]]
[[Samuel J. Friedman Theatre]]
[[Shubert Theatre (Broadway)]]
[[St. James Theatre]]
[[St James's Theatre]]
[[Stephen Sondheim Theatre]]
[[Studio 54]]
[[Theatre Royal, Bath]]
[[Times Square Theater]]
[[Vivian Beaumont Theater]]
[[Walter Kerr Theatre]]
[[Winter Garden Theatre]]
}}

====Architects====
{{#invoke:Good Articles|subsection|
[[William Adam (architect)|Adam, William]]
[[Eustace Balfour|Balfour, Eustace]]
[[Marian Cruger Coffin|Coffin, Marian Cruger]]
[[Dan Dworsky|Dworsky, Dan]]
[[Thomas Harrison (architect)|Harrison, Thomas]]
[[Zvi Hecker|Hecker, Zvi]]
[[Edward Hollamby|Hollamby, Edward]]
[[Bjarke Ingels|Ingels, Bjarke]]
[[George Meikle Kemp|Kemp, George Meikle]]
[[Vlastimil Koubek|Koubek, Vlastimil]]
[[Louis Laybourne Smith|Laybourne Smith, Louis]]
[[Geoffrey Massey|Massey, Geoffrey]]
[[Elise Mercur|Mercur, Elise]]
[[John Mylne (died 1667)|Mylne, John]]
[[Edward Graham Paley|Paley, Edward Graham]]
[[Timothy L. Pflueger|Pflueger, Timothy L.]]
[[Irving Kane Pond|Pond, Irving Kane]]
[[Antonin Raymond|Raymond, Antonin]]
[[Sharpe, Paley and Austin]]
[[Robert Schmertz (artist)|Schmertz, Robert]]
[[Kenzō Tange|Tange Kenzō]]
}}

</div>
</div>
</div><!--End Architecture level 3 GA subtopic--><noinclude>
[[Category:Lists of good articles|Art and architecture]]
</noinclude>
`;
		let output =
`							<option value="Art and architecture" disabled>==Art and architecture==</option>
							<option value="Art and architecture" disabled>===Art===</option>
							<option value="Art and architecture">====Art====</option>
							<option value="Art and architecture">=====Painting=====</option>
							<option value="Art and architecture">====Artists and art organizations====</option>
							<option value="Art and architecture" disabled>===Architecture===</option>
							<option value="Art and architecture">====Architecture====</option>
							<option value="Art and architecture">====Architecture – Bridges and tunnels====</option>
							<option value="Art and architecture">====Architecture – Buildings====</option>
							<option value="Art and architecture">=====Architecture – Buildings of the United States=====</option>
							<option value="Art and architecture">======Architecture – Buildings of Manhattan======</option>
							<option value="Art and architecture" disabled>====Architecture – Forts and fortifications====</option>
							<option value="Art and architecture">====Architecture – Hotels and inns====</option>
							<option value="Art and architecture">====Architecture – Houses and residences====</option>
							<option value="Art and architecture">====Architecture – Lighthouses====</option>
							<option value="Art and architecture">====Architecture – Memorials and monuments====</option>
							<option value="Art and architecture">====Architecture – Museums and galleries====</option>
							<option value="Art and architecture">====Architecture – Religious====</option>
							<option value="Art and architecture">====Architecture – Theatres====</option>
							<option value="Art and architecture">====Architects====</option>

`;
		expect(hg.makeTopicComboBoxOptionGroup(wikicode, topic)).toEqual(output);
	});

	it(`Should not get confused by HTML comments when deciding whether or not to disable`, () => {
		let topic = 'Warfare';
		let wikicode =
`=====Warships of Yugoslavia=====
<!-- Ship names are italicized per the MOS -->
{{#invoke:Good Articles|subsection|
`;
		let output =
`							<option value="Warfare">=====Warships of Yugoslavia=====</option>

`;
		expect(hg.makeTopicComboBoxOptionGroup(wikicode, topic)).toEqual(output);
	});

	it(`Should not get confused by whitespace when deciding whether or not to disable`, () => {
		let topic = 'History';
		let wikicode =
`=====Historical figures: politicians=====
<!--For historical politicians that were never heads of state or heads of government. Royalty and nobility belong under their own section. For living politicians, see its own section under Politics and Government--> 
{{#invoke:Good Articles|subsection|
`; // note the extra space after -->
		let output =
`							<option value="History">=====Historical figures: politicians=====</option>

`;
		expect(hg.makeTopicComboBoxOptionGroup(wikicode, topic)).toEqual(output);
	});

	it(`Should convert === This === to ===This=== (should delete spaces)`, () => {
		let topic = 'Warfare';
		let wikicode =
`===== Warships of Yugoslavia =====
{{#invoke:Good Articles|subsection|
`;
		let output =
`							<option value="Warfare">=====Warships of Yugoslavia=====</option>

`;
		expect(hg.makeTopicComboBoxOptionGroup(wikicode, topic)).toEqual(output);
	});

	it(`Should not get confused by templates when deciding whether or not to disable`, () => {
		let topic = 'Warfare';
		let wikicode =
`===== Warships of Yugoslavia =====
{{anchor|Constitutional and international law}}
{{#invoke:Good Articles|subsection|
`;
		let output =
`							<option value="Warfare">=====Warships of Yugoslavia=====</option>

`;
		expect(hg.makeTopicComboBoxOptionGroup(wikicode, topic)).toEqual(output);
	});
});