/** Moving this to its own class so it's easy to find, instead of scattered across multiple other classes. I will be updating this a lot as I discover more cases during my use of SpeciesHelper, so being able to easily find this data is useful. */
export class SpeciesHelperData {
	/** Gets a list of categories that correspond to some kind of taxa, but have a common name that is not the Latin taxa. For example, [[Category:Oriental dormice]] corresponds to [[Category:Platacanthomyidae]]. If you run SpeciesHelper without this mapping in the below object, then SpeciesHelper may incorrectly try to add a parent taxa as the category. */
	getListOfNonLatinSpeciesCategories() {
		return {
			// SENTENCE CASE AND SPACES PLEASE, usually plural
			// latin (deprecated) -> non-latin (preferred)
			Acoelomorpha: 'Acoelomorphs',
			Amazona: 'Amazon parrots',
			Aleyrodidae: 'Whiteflies',
			Anguidae: 'Anguids',
			Anisoptera: 'Dragonflies',
			Annelida: 'Annelids',
			Anura: 'Frogs',
			Araneae: 'Spiders',
			Bombus: 'Bumblebees',
			Brachyura: 'Crabs',
			Bryozoa: 'Bryozoans',
			Caprini: 'Caprids',
			Cebinae: 'Capuchin monkeys',
			Cephalopoda: 'Cephalopods',
			Cervidae: 'Deer',
			Chilopoda: 'Centipedes',
			Cirripedia: 'Barnacles',
			Cnidaria: 'Cnidarians',
			Coleoptera: 'Beetles',
			Colubridae: 'Colubrids',
			Ctenophora: 'Ctenophores',
			Curculionoidea: 'Weevils',
			Dactyloidae: 'Anoles',
			Decapodiformes: 'Squid',
			Delphinidae: 'Oceanic dolphins',
			Dendrobatidae: 'Poison dart frogs',
			Dicruridae: 'Drongos',
			Didelphimorphia: 'Opossums',
			Ephemeroptera: 'Mayflies',
			Flavobacteriia: 'Flavobacteria',
			Formicidae: 'Ants',
			Gastropoda: 'Gastropods',
			Heterokonta: 'Heterokonts',
			Insecta: 'Insects',
			Isoptera: 'Termites',
			Licmetis: 'Corellas',
			Lithodidae: 'King crabs',
			Lorisoidea: 'Lorises and galagos',
			Macropodidae: 'Macropods',
			Macronaria: 'Macronarians',
			Mammalia: 'Mammals',
			Mammuthus: 'Mammoths',
			Marmota: 'Marmots',
			Mycobacterium: 'Mycobacteria',
			Myotis: 'Mouse-eared bats',
			Mysticeti: 'Baleen whale',
			Nematoda: 'Nematodes',
			Octopoda: 'Octopuses',
			Onychophora: 'Onychophorans',
			Paeonia: 'Peonies',
			Pitheciinae: 'Sakis and uakaris',
			Platacanthomyidae: 'Oriental dormice',
			Pseudacris: 'Chorus frogs',
			Rangifer: 'Reindeer',
			Rhinocerotidae: 'Rhinoceroses',
			Rosa: 'Roses',
			Sigmodon: 'Cotton rats',
			Sitta: 'Nuthatches',
			Syrphidae: 'Hoverflies',
			Thysanoptera: 'Thrips',
			Toxodontidae: 'Toxodonts',
			Toxotes: 'Archerfish'
		};
	}

	/** Gets a list of stubs that correspond to some kind of taxa, but have a common name that is not the Latin taxa. For example, {{Bamboo-stub}} corresponds to {{Bambusoideae-stub}}. If you run SpeciesHelper without this mapping in the below object, then SpeciesHelper may incorrectly try to add a parent taxa as the stub. */
	getListOfNonLatinSpeciesStubs() {
		return {
			// SENTENCE CASE. Left side spaces, right side dashes. Usually singular.
			// latin (deprecated) -> non-latin (preferred)
			// '': 'Abyssochrysidae', // TODO: make Template:Taxonomy
			Acanthocephala: 'Acanthocephalan',
			// '': 'Agonoxeninae', // "disputed"
			// '': 'Alucitoidea', // Template:Taxonomy has a /? after it
			Ammonoidea: 'Ammonite',
			// '': 'Ancylonotini',
			Anomodontia: 'Anomodont',
			'Anthiinae (beetle)': 'AnthiinaeBeetle',
			Archosauria: 'Archosaur',
			Arthropoda: 'Arthropod',
			// '': 'Australia-asterid',
			// '': 'Australia-eudicot',
			// '': 'Australia-plant',
			// '': 'Australia-rosid',
			// '': 'Autostichinae', // TODO: make Template:Taxonomy
			Bambusoideae: 'Bamboo',
			Bryophyta: 'Bryophyte',
			Chiroptera: 'Bat',
			Anthophila: 'Bee',
			// '': 'Bicyclus', // TODO: make Template:Taxonomy
			Bikonta: 'Bikont',
			Osteichthyes: 'Bony-fish',
			Brachiopoda: 'Brachiopod',
			// '': 'Bradina', // TODO: make Template:Taxonomy
			// '': 'Bryophyte', // proposed, polyphyletic
			Bryozoa: 'Bryozoan',
			// '': 'Buccinulidae', // TODO: make Template:Taxonomy
			Rhopalocera: 'Butterfly',
			// '': 'Cabniini', // TODO: make Template:Taxonomy
			Gymnophiona: 'Caecilian',
			// '': 'Caliphyllidae', // disputed
			// '': 'Canid',
			// '': 'Carposina',
			// '': 'Ceromitia',
			// '': 'Cettiidae',
			Chamaeleonidae: 'Chameleon',
			// '': 'Chilinidae',
			Chilodontaidae: 'Chilodontidae-gastropod',
			// '': 'Chlamydephoridae',
			// '': 'Chordate',
			// '': 'Ciliate',
			// '': 'Cochlicopidae',
			Colubridae: 'Colubrids',
			Pinophyta: 'Conifer',
			// '': 'Conodont',
			Copepoda: 'Copepod',
			Crustacea: 'Crustacean',
			// '': 'Cryptoblabini',
			Sepiida: 'Cuttlefish',
			// '': 'Cycad',
			Zygoptera: 'Damselfly',
			Decapoda: 'Decapod',
			// '': 'Depressaria',
			// '': 'Dialidae',
			// '': 'Diatom',
			Dinoflagellata: 'Dinoflagellate',
			Dinosauria: 'Dinosaur',
			Diprotodontia: 'Diprotodont',
			Dermaptera: 'Earwig',
			// '': 'Eatoniellidae',
			// '': 'Eburodacrys',
			Echinodermata: 'Echinoderm',
			// '': 'Egesina',
			// '': 'Elaphidiini',
			// '': 'Eoophyla',
			// '': 'Erinaceomorpha',
			Eukaryota: 'Eukaryote',
			// '': 'Eventoedungulate',
			Fabaceae: 'Fabaceae-tree',
			Felidae: 'Feline',
			Polypodiophyta: 'Fern',
			Lampyridae: 'Firefly',
			Platyhelminthes: 'Flatworm',
			Flavobacteriia: 'Flavobacteria',
			Siphonaptera: 'Flea',
			Pteropodoidea: 'Fruit-bat',
			// '': 'Glipa',
			// '': 'Glottulinae',
			Poaceae: 'Grass',
			Marmotini: 'Ground-squirrel',
			// '': 'Haplotrematidae',
			// '': 'Hemichordate',
			// '': 'Heterokont',
			// '': 'Heteropsini',
			// '': 'Heteropsis',
			// '': 'Hydrolase',
			// '': 'Hypercalliinae',
			// '': 'Hypoptinae',
			// '': 'Ichthyosaur',
			// '': 'Isomerase',
			// '': 'Jordanoleiopus',
			// '': 'Lactobacilli',
			Lagomorpha: 'Lagomorph',
			// '': 'Lamprosema',
			Phyllostomidae: 'Leafnosed-bat',
			// '': 'Leptostylus',
			// '': 'Lepturges',
			// '': 'Ligase',
			Sarcopterygii: 'Lobefinned-fish',
			Phthiraptera: 'Louse',
			// '': 'Lyase',
			Lycophytes: 'Lycophyte',
			// '': 'Macrosphenidae',
			Magnoliids: 'Magnoliid',
			Mammalia: 'Mammal',
			Marsupialia: 'Marsupial',
			// '': 'Megomphicidae',
			// '': 'Methiini',
			// '': 'Miaenia',
			Mollusca: 'Mollusc',
			Simiiformes: 'Monkey',
			// '': 'Muroid',
			// '': 'Mythimnini',
			// '': 'Nacoleia',
			// '': 'Neoibidionini',
			// '': 'Netechma',
			Platyrrhini: 'Newworld-monkey',
			// '': 'Nitrobacteraceae',
			// '': 'Nymphicula',
			// '': 'Nyssodrysternum',
			// '': 'Obtortionidae',
			// '': 'Oddtoedungulate',
			// '': 'Oemini',
			Cercopithecoidea: 'Oldworld-monkey',
			// '': 'Olivellidae',
			// '': 'Opisthokont',
			Orchidaceae: 'Orchid',
			// '': 'Oreodera',
			// '': 'Oreohelicidae',
			// '': 'Ornithischian',
			// '': 'Ornithology',
			// '': 'Orthocomotis',
			// '': 'Ostracod',
			// '': 'Oxidoreductase',
			// '': 'Paracles',
			// '': 'Parasite-insect',
			// '': 'Parasitic-SAR',
			// '': 'Parornix',
			// '': 'Passerine',
			// '': 'Pediculariidae',
			// '': 'Permian-reptile',
			// '': 'Phyllobacteriaceae',
			// '': 'Piezocerini',
			// '': 'Piletocera',
			// '': 'Placobranchidae',
			// '': 'Placoderm',
			// '': 'Plesiosaur',
			// '': 'Poriferan',
			Eumeninae: 'Potter-wasp',
			Primates: 'Primate',
			// '': 'Prionapterygini',
			// '': 'Procerithiidae',
			// '': 'Propionibacterineae',
			// '': 'Prosoplus',
			// '': 'Protostome',
			// '': 'Psapharochrus',
			// '': 'Psaphidinae',
			// '': 'Pseudolividae',
			// '': 'Pseudonocardineae',
			Pterosauria: 'Pterosaur',
			// '': 'Pyramidulidae',
			Pyrausta: 'Pyrausta (moth)',
			// '': 'Rasboras',
			// '': 'Remizidae',
			Rodentia: 'Rodent',
			Rosids: 'Rosid',
			// '': 'Rotifer',
			Urodela: 'Salamander',
			// '': 'Saurita',
			// '': 'Sauropodomorph',
			Symphyta: 'Sawfly',
			// '': 'Scaliolidae',
			// '': 'Scaphopod',
			Scorpiones: 'Scorpion',
			Selachimorpha: 'Shark',
			Soricidae: 'Shrew',
			// '': 'Siliquariidae',
			// '': 'Siphonariidae',
			Serpentes: 'Snake',
			// '': 'Solenogaster',
			// '': 'Spirochaetae',
			// '': 'Springtail',
			Sciuridae: 'Squirrel',
			// '': 'Stenalia',
			// '': 'Stenothyridae',
			// '': 'Stictopterinae',
			// '': 'Strepsimaninae',
			// '': 'Strobilopsidae',
			// '': 'Subulinidae',
			Cygnus: 'Swan',
			// '': 'Synapsid',
			// '': 'Tardigrade',
			// '': 'Teliomycotina',
			// '': 'Therapsid',
			// '': 'Theropod',
			// '': 'Thysanura',
			// '': 'Trifurcula',
			// '': 'Trigonochlamydidae',
			// '': 'Trilobite',
			// '': 'Truncatellidae',
			Oomycota: 'Watermould',
			// '': 'Zetaproteobacteria', // TODO: create Template:Taxonomy
			Acariformes: 'Acari', // mites and ticks part 1
			Acoelomorpha: 'Xenacoelomorpha', // redirects to this parent taxon
			Actinopterygii: 'Rayfinned-fish',
			Amphibia: 'Amphibian',
			Amphipoda: 'Amphipod',
			Anatidae: 'Duck',
			Animalia: 'Animal',
			Anisoptera: 'Dragonfly',
			Annelida: 'Annelid',
			// 'Apocrita': 'Wasp', // polyphyletic
			Arachnida: 'Arachnid',
			Araneae: 'Spider',
			Arecaceae: 'Palm',
			'Alsophila (plant)': 'Alsophila-plant',
			Astacoidea: 'Crayfish',
			Asterids: 'Asterid',
			Aves: 'Bird',
			Bivalvia: 'Bivalve',
			Blattodea: 'Cockroach',
			Brachyura: 'Crab',
			Bromeliaceae: 'Bromeliad',
			Cactaceae: 'Cactus',
			Cephalopoda: 'Cephalopod',
			Cnidaria: 'Cnidarian',
			Crocidurinae: 'Whitetoothed-shrew',
			Coffea: 'Coffee',
			Coleoptera: 'Beetle',
			Ctenophora: 'Ctenophore',
			Curculionoidea: 'Weevil',
			Decapodiformes: 'Squid',
			Demospongiae: 'Demosponge',
			Ephemeroptera: 'Mayfly',
			Formicidae: 'Ant',
			Fungi: 'Fungus',
			Gastropoda: 'Gastropod',
			Gekkota: 'Gecko',
			Heterocera: 'Moth',
			Insecta: 'Insect',
			Isopoda: 'Isopod',
			Isoptera: 'Termite',
			'Mimosoid clade': 'Mimosoideae', // this one is weird. intentional though
			Monocots: 'Monocot',
			Myrmeleontidae: 'Antlion',
			Nematoda: 'Nematode',
			Nemertea: 'Nemertean',
			Octopoda: 'Octopus',
			Onychophora: 'Onychophore',
			Parasitiformes: 'Acari', // mites and ticks part 2
			Parastacoidea: 'Crayfish',
			Picidae: 'Woodpecker',
			Plantae: 'Plant',
			Psittaciformes: 'Parrot',
			Reptilia: 'Reptile',
			Salticidae: 'Jumping-spider',
			Scincidae: 'Skink',
			Siluriformes: 'Catfish',
			Soricinae: 'Redtoothed-shrew',
			// 'Squamata': 'Lizard', // paraphyletic
			Testudines: 'Turtle',
			Thysanoptera: 'Thrips',
			Trochilidae: 'Hummingbird',
			Chilopoda: 'Centipede'
		};
	}

	/** SpeciesHelper usually deletes all existing stubs, then places a very specific taxon as the stub. Below is a list of stubs to ignore/keep. The specific taxon stub will also be placed. */
	getStubSafelist() {
		return [
			// Stubs that do not 1:1 correspond with taxonomy, but that should not be deleted
			// SENTENCE CASE AND DASHES PLEASE, usually singular
			'Australia-asterid',
			'Australia-eudicot',
			'Crab',
			'Ediacaran',
			'Edicarian',
			'Fish',
			'Fruit',
			'Fruit-tree',
			'Green algae', // polyphyletic
			'Lichen',
			'Lizard', // all lizards are in squamata, but not all of squamata is lizards
			'NewZealand-plant',
			'Parasite',
			'Parasitic animal', // space instead of dash is intentional
			'Samoa',
			'Solomons',
			'Squat-lobster',
			'Tree'
		];
	}
}
